name: movie_app
description: "A Flutter app to browse and manage movie data from The Movie DB API."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #bloc&cubit for state management
  flutter_bloc: ^9.1.1
  #for display svg images =>svqPicture
  flutter_svg: ^2.2.1
  #for fetech form apis
  dio: ^5.9.0
  #Code generation for immutable classes
  freezed: ^3.2.3
  #Annotations for the freezed code-generator
  freezed_annotation: ^3.1.0
  #for dependencies injection
  get_it: ^8.2.0
  #Classes and helper functions that support JSON code generation
  json_annotation: ^4.9.0
  # retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  retrofit: ^4.7.3
  #Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.4.0
  #Contains code to deal with internationalized/localized messages, date and number formatting and parsing
  intl: ^0.20.2
  #Easy and Fast internationalizing and localization
  easy_localization: ^3.0.8
  #Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more
  flutter_native_splash: ^2.4.7
  #A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #retrofit generator is an dio client generator using source_gen
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    # App static images
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        # Variable fonts (preferred when available)
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf

        # Representative static weights
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
